# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yet Another Ranting Developer
email: adonis.settouf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is a simple blog relating to the life of a developer, trying to have fun in this desperately
  corporate world (and don't try to tell me having to create a ssh inside a ssh inside a ssh session is fun!)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asettouf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  asettouf
# Build settings
markdown: kramdown
#theme: minima

#theme: jekyll-theme-hacker
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
disqus:
  shortname: asettouf-github-io
incremental: true
defaults:
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # previously `post` in Jekyll 2.2.
  values:
    layout: "default"
